package com.courtrank.authService.application.ports.audit;

public enum AuditEventType {
    AUTH_SIGN_UP_SUCCESS,
    AUTH_SIGN_UP_CONFLICT,
    AUTH_SIGN_IN_SUCCESS,
    AUTH_SIGN_IN_FAILED,
    AUTH_SIGN_IN_BLOCKED,
    AUTH_SIGN_IN_FORBIDDEN,
    AUTH_SIGN_IN_UNVERIFIED_EMAIL,
    AUTH_PASSWORD_CHANGED,
    AUTH_PASSWORD_RESET_REQUESTED,
    AUTH_PASSWORD_RESET_OTP_VERIFIED,
    AUTH_PASSWORD_RESET_COMPLETED,
    AUTH_VERIFICATION_EMAIL_SENT,
    AUTH_VERIFICATION_EMAIL_RESENT,
    AUTH_EMAIL_VERIFIED,
    AUTH_USER_DELETED,
    AUTH_DATA_CONSENT_UPDATED,
    AUTH_SESSIONS_LISTED,
    AUTH_SESSION_REFRESHED,
    AUTH_REFRESH_REUSE_DETECTED,
    AUTH_SESSION_REVOKED,
    AUTH_ALL_SESSIONS_REVOKED,
    AUTH_SIGN_UP_RESTORED_USER
}
