package com.courtrank.socialService.application.ports.audit;

public enum SocialAuditEventType {
    FOLLOW_CREATE_SKIPPED_ALREADY_EXISTS,
    FOLLOW_CREATE_FAILED_FOLLOWER_NOT_FOUND,
    FOLLOW_CREATE_FAILED_TARGET_NOT_FOUND,
    FOLLOW_CREATE_FAILED_BLOCKED,
    FOLLOW_CREATED_ACCEPTED,
    FOLLOW_CREATED_PENDING,
    FOLLOW_ACCEPT_FAILED_NOT_FOUND,
    FOLLOW_ACCEPTED,
    FOLLOW_REJECT_FAILED_NOT_FOUND,
    FOLLOW_REJECTED,
    FOLLOW_REMOVE_FAILED_NOT_FOUND,
    FOLLOW_REMOVED,
    FOLLOWER_REMOVE_FAILED_NOT_FOUND,
    FOLLOWER_REMOVED,
    BLOCK_CREATE_SKIPPED_ALREADY_EXISTS,
    BLOCK_CREATE_FAILED_BLOCKER_NOT_FOUND,
    BLOCK_CREATE_FAILED_TARGET_NOT_FOUND,
    BLOCK_CREATED,
    BLOCK_REMOVE_SKIPPED_NOT_FOUND,
    BLOCK_REMOVED
}
